name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test: # Renamed job for clarity

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Updated to JDK 17
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Android Lint
      run: ./gradlew lintDebug # Or your specific lint task, e.g., lintRelease

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest # Or your specific test task, e.g., testReleaseUnitTest

    - name: Build with Gradle
      run: ./gradlew assembleDebug # Or your specific build task, e.g., assembleRelease or bundleRelease

    - name: Build and Sign Release APK
      # The environment variables are used by the build.gradle signingConfig
      env:
        ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      run: ./gradlew bundleRelease


    - name: Upload Signed Release AAB
      uses: actions/upload-artifact@v4
      with:
        name: AAB and R8
        path: |
          app/build/outputs/bundle/release/app-release.aab
          app/build/outputs/mapping/release/mapping.txt
          app/build/outputs/mapping/release/seeds.txt
          app/build/outputs/mapping/release/usage.txt
          app/build/outputs/mapping/release/configuration.txt
        retention-days: 7
